<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-03-21T13:33:05 IST" name="SampleAutomationTest Suite" finished-at="2023-03-21T13:33:31 IST" duration-ms="26405">
    <groups>
    </groups>
    <test started-at="2023-03-21T13:33:05 IST" name="Login to the application with valid credentials sauce50" finished-at="2023-03-21T13:33:31 IST" duration-ms="26405">
      <class name="TestCase">
        <test-method is-config="true" signature="setUp()[pri:0, instance:TestCase@59505b48]" started-at="2023-03-21T13:33:05 IST" name="setUp" finished-at="2023-03-21T13:33:08 IST" duration-ms="3688" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="Login_to_the_application_with_invalid_credentials_sauce51()[pri:0, instance:TestCase@59505b48]" started-at="2023-03-21T13:33:08 IST" name="Login_to_the_application_with_invalid_credentials_sauce51" finished-at="2023-03-21T13:33:20 IST" duration-ms="11469" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login_to_the_application_with_invalid_credentials_sauce51 -->
        <test-method signature="Login_to_the_application_with_valid_credentials_sauce50()[pri:0, instance:TestCase@59505b48]" started-at="2023-03-21T13:33:20 IST" name="Login_to_the_application_with_valid_credentials_sauce50" finished-at="2023-03-21T13:33:30 IST" duration-ms="10448" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Productss] but found [Products]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Productss] but found [Products]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at TestCase.Login_to_the_application_with_valid_credentials_sauce50(TestCase.java:29)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login_to_the_application_with_valid_credentials_sauce50 -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:TestCase@59505b48]" started-at="2023-03-21T13:33:30 IST" name="tearDown" finished-at="2023-03-21T13:33:31 IST" duration-ms="762" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- TestCase -->
    </test> <!-- Login to the application with valid credentials sauce50 -->
  </suite> <!-- SampleAutomationTest Suite -->
</testng-results>
